name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 添加这一行以授予 write 权限
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GITHUB_TOKEN
          publish_dir: ./docs-dist
